name: Android Release

on:

  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: 'android build type [apk,bundle]'
        required: true
        default: 'apk'
        options:
          - apk
          - bundle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.x"
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build bundle
        if: github.event.inputs.build_type == 'bundle'
        run: flutter build appbundle

      - name: start release build apk
        if: github.event.inputs.build_type == 'apk'
        run: flutter build apk


      - name: Upload bundle Build Files
        if: github.event.inputs.build_type == 'apk'
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: ./build/app/outputs/flutter-apk

      - name: Upload bundle Build Files
        if: github.event.inputs.build_type == 'bundle'
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: ./build/app/outputs/bundle/release
